// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/person.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type More struct {
	C                    int64    `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	D                    int64    `protobuf:"varint,2,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *More) Reset()         { *m = More{} }
func (m *More) String() string { return proto.CompactTextString(m) }
func (*More) ProtoMessage()    {}
func (*More) Descriptor() ([]byte, []int) {
	return fileDescriptor_691029fcf881525d, []int{0}
}

func (m *More) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_More.Unmarshal(m, b)
}
func (m *More) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_More.Marshal(b, m, deterministic)
}
func (m *More) XXX_Merge(src proto.Message) {
	xxx_messageInfo_More.Merge(m, src)
}
func (m *More) XXX_Size() int {
	return xxx_messageInfo_More.Size(m)
}
func (m *More) XXX_DiscardUnknown() {
	xxx_messageInfo_More.DiscardUnknown(m)
}

var xxx_messageInfo_More proto.InternalMessageInfo

func (m *More) GetC() int64 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *More) GetD() int64 {
	if m != nil {
		return m.D
	}
	return 0
}

type Request struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_691029fcf881525d, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Request) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type Response struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_691029fcf881525d, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type Info struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_691029fcf881525d, []int{3}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Info) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*More)(nil), "api.More")
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Response)(nil), "api.Response")
	proto.RegisterType((*Info)(nil), "api.Info")
}

func init() { proto.RegisterFile("api/person.proto", fileDescriptor_691029fcf881525d) }

var fileDescriptor_691029fcf881525d = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xe9, 0xae, 0x76, 0x58, 0x61, 0x19, 0x44, 0x16, 0x4f, 0x1a, 0x50, 0x3c, 0xc5,
	0x45, 0x9f, 0x60, 0x8f, 0x1e, 0x7a, 0x89, 0x4f, 0x90, 0x36, 0xa3, 0x04, 0x6a, 0x13, 0x93, 0xd4,
	0x8b, 0x2f, 0x2f, 0x49, 0xd3, 0x83, 0x17, 0x6f, 0xf9, 0xf8, 0x3f, 0x32, 0xff, 0x0c, 0xec, 0xb5,
	0xb7, 0x4f, 0x9e, 0x42, 0x74, 0x93, 0xf4, 0xc1, 0x25, 0x87, 0x5c, 0x7b, 0x2b, 0x04, 0x34, 0x9d,
	0x0b, 0x84, 0x3b, 0x60, 0xc3, 0x81, 0xdd, 0xb2, 0x47, 0xae, 0xd8, 0x90, 0xc9, 0x1c, 0xce, 0x16,
	0x32, 0xe2, 0x1e, 0xce, 0x15, 0x7d, 0xcd, 0x14, 0x53, 0x0e, 0xf4, 0xaa, 0xe9, 0x4c, 0xfd, 0xaa,
	0xf5, 0x42, 0xc0, 0x85, 0xa2, 0xe8, 0xdd, 0x14, 0x09, 0xaf, 0x61, 0x1b, 0x28, 0xce, 0x63, 0xaa,
	0x72, 0x25, 0x21, 0xa1, 0x79, 0x9d, 0xde, 0x1d, 0x5e, 0xc1, 0x26, 0xd9, 0x34, 0x52, 0x89, 0x5b,
	0xb5, 0x00, 0xee, 0x81, 0x7f, 0xc6, 0x8f, 0xf2, 0x63, 0xab, 0xf2, 0xf3, 0xf9, 0x07, 0xe0, 0x64,
	0xcc, 0x1b, 0x85, 0x6f, 0x3b, 0x10, 0x0a, 0xe0, 0x27, 0x63, 0x70, 0x27, 0xb5, 0xb7, 0xb2, 0x56,
	0xba, 0xb9, 0xac, 0x54, 0x27, 0x3f, 0xc0, 0xa6, 0x9b, 0xc7, 0x64, 0xff, 0xb5, 0x8e, 0x0c, 0xef,
	0xa0, 0x49, 0x65, 0xa3, 0x3f, 0x5a, 0x5b, 0x28, 0x57, 0x3c, 0xb2, 0x7e, 0x5b, 0xee, 0xf4, 0xf2,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x38, 0x06, 0xb6, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Multi(ctx context.Context, in *Request, opts ...grpc.CallOption) (AddService_MultiClient, error)
	Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (AddService_TestClient, error)
}

type addServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClient(cc *grpc.ClientConn) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.AddService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Multi(ctx context.Context, in *Request, opts ...grpc.CallOption) (AddService_MultiClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AddService_serviceDesc.Streams[0], "/api.AddService/Multi", opts...)
	if err != nil {
		return nil, err
	}
	x := &addServiceMultiClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AddService_MultiClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type addServiceMultiClient struct {
	grpc.ClientStream
}

func (x *addServiceMultiClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *addServiceClient) Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (AddService_TestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AddService_serviceDesc.Streams[1], "/api.AddService/test", opts...)
	if err != nil {
		return nil, err
	}
	x := &addServiceTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AddService_TestClient interface {
	Recv() (*Info, error)
	grpc.ClientStream
}

type addServiceTestClient struct {
	grpc.ClientStream
}

func (x *addServiceTestClient) Recv() (*Info, error) {
	m := new(Info)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	Add(context.Context, *Request) (*Response, error)
	Multi(*Request, AddService_MultiServer) error
	Test(*Request, AddService_TestServer) error
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) Add(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedAddServiceServer) Multi(req *Request, srv AddService_MultiServer) error {
	return status.Errorf(codes.Unimplemented, "method Multi not implemented")
}
func (*UnimplementedAddServiceServer) Test(req *Request, srv AddService_TestServer) error {
	return status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AddService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Multi_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AddServiceServer).Multi(m, &addServiceMultiServer{stream})
}

type AddService_MultiServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type addServiceMultiServer struct {
	grpc.ServerStream
}

func (x *addServiceMultiServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _AddService_Test_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AddServiceServer).Test(m, &addServiceTestServer{stream})
}

type AddService_TestServer interface {
	Send(*Info) error
	grpc.ServerStream
}

type addServiceTestServer struct {
	grpc.ServerStream
}

func (x *addServiceTestServer) Send(m *Info) error {
	return x.ServerStream.SendMsg(m)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddService_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Multi",
			Handler:       _AddService_Multi_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "test",
			Handler:       _AddService_Test_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/person.proto",
}
